packages:
  - "."
  - "web"

allowBuilds:
  better-sqlite3: true
  electron-winstaller: true
  esbuild: true
  fsevents: false

strictDepBuilds: true

overrides:
  "@esbuild-kit/core-utils>esbuild": "^0.25.0"
