// Generates a `kith-space` wrapper script under ~/.kith-space/bin and injects it into the spawned agent's PATH.
// Agents call `kith-space ...` from their shell/bash tool → routed to this repo's CLI.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { binDir } from "../paths.js";

export function ensureKithSpaceBin(): string {
  const dir = binDir();
  fs.mkdirSync(dir, { recursive: true });

  const here = path.dirname(fileURLToPath(import.meta.url)); // repo: .../src/daemon · bundled: .../dist
  // Bundled/npm mode (@fancyboi999/kith-space-daemon): the agent CLI ships as a sibling bundle next to the daemon and
  // runs directly with node — there's no repo source or tsx on disk. Repo mode: run the TS source via tsx.
  const bundledCli = path.join(here, "agent-cli.mjs");
  let cmd: string;
  if (fs.existsSync(bundledCli)) {
    cmd = `exec node ${JSON.stringify(bundledCli)} "$@"`;
  } else {
    const cliPath = path.resolve(here, "../cli/index.ts");
    const projectRoot = path.resolve(here, "../.."); // .../kith-space
    const tsxBin = path.join(projectRoot, "node_modules", ".bin", "tsx");
    const runner = fs.existsSync(tsxBin) ? tsxBin : "npx tsx"; // prefer local tsx, fallback to npx
    cmd = `exec ${runner.includes(" ") ? runner : JSON.stringify(runner)} ${JSON.stringify(cliPath)} "$@"`;
  }

  const wrapper = path.join(dir, "kith-space");
  const sh = `#!/bin/sh\n# kith-space agent CLI wrapper (auto-generated by daemon)\n${cmd}\n`;
  fs.writeFileSync(wrapper, sh);
  fs.chmodSync(wrapper, 0o755);
  return dir;
}
