// Generates the host-native `kith-space` wrapper under ~/.kith-space/bin and injects it into agent PATH.
// Windows receives only kith-space.cmd; Linux/macOS receive the executable POSIX wrapper.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { binDir } from "../paths.js";

export function buildBundledCliCommand(executable: string, bundledCli: string, electronRunAsNode: boolean): string {
  const runner = `${JSON.stringify(executable)} ${JSON.stringify(bundledCli)} "$@"`;
  return electronRunAsNode
    ? `exec env ELECTRON_RUN_AS_NODE=1 ${runner}`
    : `exec ${runner}`;
}

export function buildBundledCliCmdCommand(executable: string, bundledCli: string, electronRunAsNode: boolean): string {
  const lines = ["@echo off", "setlocal", "chcp 65001 >nul"];
  if (electronRunAsNode) lines.push('set "ELECTRON_RUN_AS_NODE=1"');
  lines.push(`"${executable}" "${bundledCli}" %*`, "exit /b %ERRORLEVEL%", "");
  return lines.join("\r\n");
}

export function ensureKithSpaceBin(): string {
  const dir = binDir();
  fs.mkdirSync(dir, { recursive: true });

  const here = path.dirname(fileURLToPath(import.meta.url)); // repo: .../src/daemon · bundled: .../dist
  // Packaged Desktop: the agent CLI is a sibling of the Worker bundle and reuses Electron's executable in
  // Node mode. Repo mode keeps using the TS source through the developer's local Node/tsx installation.
  const bundledCli = path.join(here, "agent-cli.mjs");
  let cmd: string;
  let cmdWindows: string | null = null;
  if (fs.existsSync(bundledCli)) {
    const electronRunAsNode = !!process.versions.electron;
    cmd = buildBundledCliCommand(process.execPath, bundledCli, electronRunAsNode);
    if (process.platform === "win32") {
      cmdWindows = buildBundledCliCmdCommand(process.execPath, bundledCli, electronRunAsNode);
    }
  } else {
    const cliPath = path.resolve(here, "../cli/index.ts");
    const projectRoot = path.resolve(here, "../.."); // .../kith-space
    const tsxBin = path.join(projectRoot, "node_modules", ".bin", "tsx");
    const runner = fs.existsSync(tsxBin) ? tsxBin : "npx tsx"; // prefer local tsx, fallback to npx
    cmd = `exec ${runner.includes(" ") ? runner : JSON.stringify(runner)} ${JSON.stringify(cliPath)} "$@"`;
    if (process.platform === "win32") {
      const tsxCmd = `${tsxBin}.cmd`;
      const command = fs.existsSync(tsxCmd)
        ? `call "${tsxCmd}" "${cliPath}" %*`
        : `call npx.cmd tsx "${cliPath}" %*`;
      cmdWindows = ["@echo off", "setlocal", "chcp 65001 >nul", command, "exit /b %ERRORLEVEL%", ""].join("\r\n");
    }
  }

  const wrapper = path.join(dir, "kith-space");
  if (process.platform === "win32") {
    if (!cmdWindows) throw new Error("Windows kith-space CLI wrapper was not configured");
    fs.writeFileSync(`${wrapper}.cmd`, cmdWindows);
    fs.rmSync(wrapper, { force: true }); // remove the pre-fix POSIX file that triggered Windows Open With
  } else {
    const sh = `#!/bin/sh\n# kith-space agent CLI wrapper (auto-generated by daemon)\n${cmd}\n`;
    fs.writeFileSync(wrapper, sh);
    fs.chmodSync(wrapper, 0o755);
  }
  return dir;
}
