// Generates a `kith-space` wrapper script under ~/.kith-space/bin and injects it into the spawned agent's PATH.
// Agents call `kith-space ...` from their shell/bash tool → routed to this repo's CLI.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { binDir } from "../paths.js";

export function buildBundledCliCommand(executable: string, bundledCli: string, electronRunAsNode: boolean): string {
  const runner = `${JSON.stringify(executable)} ${JSON.stringify(bundledCli)} "$@"`;
  return electronRunAsNode
    ? `exec env ELECTRON_RUN_AS_NODE=1 ${runner}`
    : `exec ${runner}`;
}

export function buildBundledCliCmdCommand(executable: string, bundledCli: string, electronRunAsNode: boolean): string {
  const lines = ["@echo off", "setlocal"];
  if (electronRunAsNode) lines.push('set "ELECTRON_RUN_AS_NODE=1"');
  lines.push(`"${executable}" "${bundledCli}" %*`, "exit /b %ERRORLEVEL%", "");
  return lines.join("\r\n");
}

export function ensureKithSpaceBin(): string {
  const dir = binDir();
  fs.mkdirSync(dir, { recursive: true });

  const here = path.dirname(fileURLToPath(import.meta.url)); // repo: .../src/daemon · bundled: .../dist
  // Packaged Desktop: the agent CLI is a sibling of the Worker bundle and reuses Electron's executable in
  // Node mode. Repo mode keeps using the TS source through the developer's local Node/tsx installation.
  const bundledCli = path.join(here, "agent-cli.mjs");
  let cmd: string;
  let cmdWindows: string | null = null;
  if (fs.existsSync(bundledCli)) {
    const electronRunAsNode = !!process.versions.electron;
    cmd = buildBundledCliCommand(process.execPath, bundledCli, electronRunAsNode);
    cmdWindows = buildBundledCliCmdCommand(process.execPath, bundledCli, electronRunAsNode);
  } else {
    const cliPath = path.resolve(here, "../cli/index.ts");
    const projectRoot = path.resolve(here, "../.."); // .../kith-space
    const tsxBin = path.join(projectRoot, "node_modules", ".bin", "tsx");
    const runner = fs.existsSync(tsxBin) ? tsxBin : "npx tsx"; // prefer local tsx, fallback to npx
    cmd = `exec ${runner.includes(" ") ? runner : JSON.stringify(runner)} ${JSON.stringify(cliPath)} "$@"`;
  }

  const wrapper = path.join(dir, "kith-space");
  const sh = `#!/bin/sh\n# kith-space agent CLI wrapper (auto-generated by daemon)\n${cmd}\n`;
  fs.writeFileSync(wrapper, sh);
  fs.chmodSync(wrapper, 0o755);
  if (cmdWindows) fs.writeFileSync(path.join(dir, "kith-space.cmd"), cmdWindows);
  return dir;
}
