import type { SkillCatalog, SkillMetadata } from "./contracts.js";

const SKILL_REGISTRY: Record<string, SkillMetadata> = {
  design_brief: {
    skillKey: "design_brief",
    displayName: "Design Brief",
    category: "foundation",
    whenToUse: "Starting any new design from scratch",
    description: "Structured design brief template covering purpose, audience, emotion, visual thesis, and composition archetype",
    priority: "P0",
  },
  composition: {
    skillKey: "composition",
    displayName: "Composition",
    category: "foundation",
    whenToUse: "Making layout and composition decisions",
    description: "Layout archetypes (hero, split, grid, etc.) and composition rules (balance, focal point, rhythm)",
    priority: "P0",
  },
  color: {
    skillKey: "color",
    displayName: "Color",
    category: "foundation",
    whenToUse: "Choosing color palette or making color decisions",
    description: "Color theory, palette strategies (monochrome, analogous, complementary, triadic), and emotional associations",
    priority: "P0",
  },
  typography: {
    skillKey: "typography",
    displayName: "Typography",
    category: "foundation",
    whenToUse: "Choosing fonts or setting type hierarchy",
    description: "Type ladders (hero/title/body/caption), font pairing rules, and hierarchy principles",
    priority: "P0",
  },
  anti_ai_slop: {
    skillKey: "anti_ai_slop",
    displayName: "Anti-AI Slop",
    category: "foundation",
    whenToUse: "Always (implicit check before finalizing)",
    description: "Common AI design clichés to avoid: purple-blue gradients, glassmorphism, isometric function cards, random particles, etc.",
    priority: "P0",
  },
  polish: {
    skillKey: "polish",
    displayName: "Polish",
    category: "foundation",
    whenToUse: "Final refinement before completion",
    description: "Refinement checklist and self-review criteria",
    relatedSkills: ["anti_ai_slop", "composition", "typography"],
    priority: "P1",
  },
  design_review: {
    skillKey: "design_review",
    displayName: "Design Review",
    category: "foundation",
    whenToUse: "Reviewing completed work before settle (QA rubric)",
    description: "Dimensional craft scoring rubric: composition/hierarchy/typography/color/consistency/content/originality with caps and pass thresholds",
    priority: "P1",
  },
  design_system: {
    skillKey: "design_system",
    displayName: "Design System",
    category: "foundation",
    whenToUse: "Locking type/spacing/radius/color roles before paint",
    description: "Token sheet + hierarchy ratios; paint from the sheet, not random per-node numbers",
    relatedSkills: ["typography", "color"],
    priority: "P1",
  },
  imagery: {
    skillKey: "imagery",
    displayName: "Imagery",
    category: "foundation",
    whenToUse: "Deciding bitmap vs vector and hero coverage",
    description: "Bitmap vs vector guidance, hero coverage (60-85%), no baked titles unless asked",
    priority: "P1",
  },
  layout: {
    skillKey: "layout",
    displayName: "Layout",
    category: "foundation",
    whenToUse: "Executing spacing/grid/alignment after composition",
    description: "Spacing rhythm, grid, alignment, whitespace; keep ≥15% empty space on posters",
    priority: "P1",
  },
  responsive: {
    skillKey: "responsive",
    displayName: "Responsive",
    category: "foundation",
    whenToUse: "Multi-breakpoint web / app surfaces",
    description: "Breakpoints and stacking; same IA across desktop/tablet/mobile, not a cropped poster",
    priority: "P1",
  },
  visual_direction: {
    skillKey: "visual_direction",
    displayName: "Visual Direction",
    category: "foundation",
    whenToUse: "Locking visual thesis + Style DNA after the brief",
    description: "Visual thesis (one falsifiable sentence) + Style DNA slots (material/geometry/lighting/texture/density/palette/typography/imagery)",
    relatedSkills: ["imagery"],
    priority: "P1",
  },
  poster_craft: {
    skillKey: "poster_craft",
    displayName: "Poster Craft",
    category: "domains",
    whenToUse: "Creating posters, roll-ups, or key visuals",
    description: "End-to-end poster design playbook: brief → art direction → layout → execution → review",
    relatedSkills: ["design_brief", "composition", "color", "typography", "anti_ai_slop"],
    priority: "P0",
    triggers: { promptIncludesAny: ["海报", "poster", "易拉宝", "roll-up", "rollup", "展架", "音乐节", "1080x1920"] },
  },
  landing_page: {
    skillKey: "landing_page",
    displayName: "Landing Page",
    category: "domains",
    whenToUse: "Designing landing pages or homepage hero sections",
    description: "Landing page design playbook: hero section, value props, social proof, CTA hierarchy",
    relatedSkills: ["design_brief", "composition", "typography"],
    priority: "P1",
    triggers: { promptIncludesAny: ["落地页", "官网", "landing", "homepage", "网站", "网页", "营销页", "首屏", "Hero"] },
  },
  banner_ad: {
    skillKey: "banner_ad",
    displayName: "Banner Ad",
    category: "domains",
    whenToUse: "Creating banner ads or social media ads",
    description: "Banner ad design playbook: attention-grabbing within size constraints, clear CTA",
    relatedSkills: ["design_brief", "color", "typography"],
    priority: "P1",
    triggers: { promptIncludesAny: ["banner", "横幅", "广告条", "通栏", "顶通", "KV", "广告位"] },
  },
  awesome_design_md: {
    skillKey: "awesome_design_md",
    displayName: "Awesome DesignMD",
    category: "domains",
    whenToUse: "Injecting or switching a brand visual system",
    description: "Brand visual parameter sheet (tone/colors/type/radius/spacing/surfaces/forbidden); paint against one sheet",
    relatedSkills: ["garden_style", "shadcn_ui"],
    priority: "P1",
  },
  dashboard_ui: {
    skillKey: "dashboard_ui",
    displayName: "Dashboard / admin UI",
    category: "domains",
    whenToUse: "Dashboard / console / admin surfaces",
    description: "Task-first dashboard IA: primary info → secondary → context → action; never four equal KPI cards",
    relatedSkills: ["icon_set", "image_gen", "mobile_app_ui", "shadcn_ui"],
    priority: "P1",
    triggers: { promptIncludesAny: ["dashboard", "后台", "控制台", "admin", "console", "看板", "KPI", "analytics", "管理端", "仪表盘", "数据仪表", "折线图", "1440x900"] },
  },
  ecommerce_surface: {
    skillKey: "ecommerce_surface",
    displayName: "Ecommerce surfaces",
    category: "domains",
    whenToUse: "Ecommerce hero / PDP surfaces",
    description: "Product-first hero and PDP: subject ~40-60% weight, module order, sparse badges",
    relatedSkills: ["icon_set", "image_gen", "shadcn_ui"],
    priority: "P1",
    triggers: { promptIncludesAny: ["电商", "商详", "PDP", "详情页", "ecommerce", "product hero", "加购"] },
  },
  garden_style: {
    skillKey: "garden_style",
    displayName: "Garden Style",
    category: "domains",
    whenToUse: "Bold aesthetic direction / tone / atmosphere",
    description: "Style recipe engine: direction catalog (minimal/editorial/industrial/organic/luxury/festive/…) + anti-defaults",
    relatedSkills: ["awesome_design_md", "image_gen", "landing_page", "poster_craft"],
    priority: "P1",
    triggers: { promptIncludesAny: ["调性", "氛围感", "视觉方向", "审美方向", "节日氛围", "插画风", "garden style", "aesthetic direction", "style direction", "visual direction", "festive", "editorial look"] },
  },
  icon_set: {
    skillKey: "icon_set",
    displayName: "Icon / mark set",
    category: "domains",
    whenToUse: "Icon sets / app icons / UI glyphs",
    description: "Consistent vector icon grids: shared stroke/corner/cell, optical balance",
    relatedSkills: ["dashboard_ui", "image_gen", "mobile_app_ui", "shadcn_ui"],
    priority: "P1",
    triggers: { promptIncludesAny: ["图标", "icon", "icon set", "favicon", "glyph", "符号", "icon grid", "线性图标", "图标组"] },
  },
  image_gen: {
    skillKey: "image_gen",
    displayName: "Image generation",
    category: "domains",
    whenToUse: "Specifying generated bitmaps for hero / atmosphere / product plates",
    description: "Bitmap specification: brief → thesis → composition → material → lighting; no baked titles unless asked",
    relatedSkills: ["banner_ad", "icon_set", "landing_page", "poster_craft"],
    priority: "P1",
  },
  long_scroll: {
    skillKey: "long_scroll",
    displayName: "Long image / scroll story",
    category: "domains",
    whenToUse: "Tall continuous scroll boards",
    description: "Scroll storytelling: hook → chapters → close/CTA; mobile width, chapter rhythm",
    relatedSkills: ["garden_style", "image_gen"],
    priority: "P1",
    triggers: { promptIncludesAny: ["长图", "long image", "长截图", "scroll story", "条漫", "超长图", "长页"] },
  },
  mobile_app_ui: {
    skillKey: "mobile_app_ui",
    displayName: "Mobile / H5 app UI",
    category: "domains",
    whenToUse: "Mobile / H5 app screens",
    description: "Mobile screens: safe areas, single column, thumb-zone CTA, top/bottom chrome",
    relatedSkills: ["icon_set", "image_gen", "shadcn_ui"],
    priority: "P1",
    triggers: { promptIncludesAny: ["H5", "手机", "App", "iOS", "Android", "小程序", "mobile app", "移动端", "登录页", "390x844", "390×844", "健身", "打卡", "底部 Tab", "底部Tab"] },
  },
  resume_layout: {
    skillKey: "resume_layout",
    displayName: "Resume / CV",
    category: "domains",
    whenToUse: "Resume / CV documents",
    description: "Resume layout: scan path, ≤2 columns, type scale, section rhythm — not poster decoration",
    relatedSkills: ["image_gen", "shadcn_ui"],
    priority: "P1",
    triggers: { promptIncludesAny: ["简历", "履历", "resume", "CV", "curriculum vitae"] },
  },
  shadcn_ui: {
    skillKey: "shadcn_ui",
    displayName: "shadcn/ui",
    category: "domains",
    whenToUse: "Composing product UI with shadcn-like grammar",
    description: "shadcn-like UI composition: semantic roles, patterns (button/input/card/table/nav/dialog), labeled states",
    relatedSkills: ["awesome_design_md", "dashboard_ui", "landing_page", "mobile_app_ui"],
    priority: "P1",
  },
  type_specimen: {
    skillKey: "type_specimen",
    displayName: "Typography / font specimen",
    category: "domains",
    whenToUse: "Font specimens / pairings / weight ladders",
    description: "Catalog-only type specimens: giant sample → metrics → body; type is the hero",
    relatedSkills: ["garden_style", "image_gen"],
    priority: "P1",
    triggers: { promptIncludesAny: ["字体", "typography", "font specimen", "字样", "字体展示", "type specimen", "font pairing"] },
  },
};

export function getSkillMetadata(skillKey: string): SkillMetadata | undefined {
  return SKILL_REGISTRY[skillKey];
}

export function listSkills(): SkillCatalog {
  const all = Object.values(SKILL_REGISTRY);
  return {
    foundation: all.filter((skill) => skill.category === "foundation"),
    domains: all.filter((skill) => skill.category === "domains"),
  };
}

export function getAllSkillKeys(): string[] {
  return Object.keys(SKILL_REGISTRY);
}
